// <auto-generated />
namespace MonoTask.Infrastructure.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EFnavigations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EFnavigations));
        
        string IMigrationMetadata.Id
        {
            get { return "202101051538279_EF navigations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
